### PR TITLE
Issue/69/ci

### LINKED ISSUE #69: Incorporate integration testing with docker on travis
Although this seems to almost be complete in https://github.com/alan-turing-institute/dodo/pull/64 there appears to be errors relating how the travis script is configured.

This should be straight forward to alter such that tests are run using a `docker-compose.yml` file inspired from https://github.com/alan-turing-institute/twitcher/pull/8/files

### PR DESCRIPTION
**Pull request by tallamjr**
Fixes #69 

This allows for integrated testing to be run on Travis with, and without `docker` configured

### CODE REVIEW

**Comment by tallamjr** [comment]
As I am not really familiar with R, I'm not actually sure that `rdodo` is being tested properly, however Python is, albeit for only `python == 3.6`. 

For `python == 3.7` to be tested as well, a very minor change is required, the reason it taken out was to do with Python not being supported on macOS on travis, but there is any easy workaround if desired

**Comment by rkm** [comment]
Hey, some of the Python tests seem to have failed even though the whole build passed: https://travis-ci.org/alan-turing-institute/dodo/jobs/573956076. Not had a chance to look in detail for why the tests are failing, but the build still passes because the `pytest` exit code is being hidden:
```bash
> "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then docker-compose up -d; sleep 20; cd $DODO_HOME/PyDodo/ && pytest -vs tests/ && cd - ; docker-compose down; fi"
                                                                                                                                   ^^
```

**Comment by thobson88** [comment]
It doesn't look like the rdodo tests are being run, but it's fine to just support the pydodo tests for now. I'll create a separate ticket for rdodo CI and then experiment with existing travis config plus the advice at https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/

**Comment by tallamjr** [comment]
Thanks @rkm , I hadn't realised that last night it was not actually catching the errors. 

I have made modifications to the travis script as well as adding a separate file that can ensure we catch the pytest exit codes. This has now "successfully failed" here : https://travis-ci.com/alan-turing-institute/dodo/jobs/226618771 😄

**Comment by tallamjr** [comment]
> It doesn't look like the rdodo tests are being run, but it's fine to just support the pydodo tests for now. I'll create a separate ticket for rdodo CI and then experiment with the existing travis config plus the advice at https://jef.works/blog/2019/02/17/automate-testing-of-your-R-package/

I'll try to incorporate this as well, hopefully it is just a couple of additions, then I can rebase the previous commits and include with this PR.

* Changing to `[WIP]` for now until R testing is included also

**Comment by tallamjr** [comment]
Cool, it looks like it is able to run both Python and the R checks together and is successfully failing as can be seen here: https://travis-ci.com/alan-turing-institute/dodo/jobs/226710567

I will mark as _ready_ by removing the `[WIP]`

**Comment by tallamjr** [comment]
Merged following discussion with @thobson88

**Pull request merged**
